export const LOGIN = "LOGIN";
export const POST_ROOM_MESSAGES = "POST_ROOM_MESSAGES";

export const SEARCH_PROFILE_PENDING = "SEARCH_PROFILE_PENDING";
export const SEARCH_PROFILE_FULFILLED = "SEARCH_PROFILE_FULFILLED";
export const SEARCH_PROFILE_REJECTED = "SEARCH_PROFILE_REJECTED";

export const FETCH_ROOMS_PENDING = "FETCH_ROOMS_PENDING";
export const FETCH_ROOMS_FULFILLED = "FETCH_ROOMS_FULFILLED";
export const FETCH_ROOMS_REJECTED = "FETCH_ROOMS_REJECTED";

export const FETCH_ROOM_DETAIL_PENDING = "FETCH_ROOM_DETAIL_PENDING";
export const FETCH_ROOM_DETAIL_FULFILLED = "FETCH_ROOM_DETAIL_FULFILLED";
export const FETCH_ROOM_DETAIL_REJECTED = "FETCH_ROOM_DETAIL_REJECTED";

export const FETCH_ROOM_MESSAGES_PENDING = "FETCH_ROOM_MESSAGES_PENDING";
export const FETCH_ROOM_MESSAGES_FULFILLED = "FETCH_ROOM_MESSAGES_FULFILLED";
export const FETCH_ROOM_MESSAGES_REJECTED = "FETCH_ROOM_MESSAGES_REJECTED";

export const UPDATE_ACTIVE_USER = "UPDATE_ACTIVE_USER";
